### ISSUE TITLE
Gmail Upload Nits

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/archive.prove.email#105]
**Gmail Upload improvements**: Fix the Google auth flow interface for Gmail upload. You have to click sign in twice due to redirects, vs that button should just be on the /contribute page and not redirect even once. It should also callback to https://archive.prove.email/upload_gmail, but currently it goes to https://registry.prove.email.

**Comment by foolo** [comment]
Hi @Divide-By-0 , I can look at these if you report them as two separate issues. I don't want to discuss or fix two different problems in the same issue because it just gets too confusing and messy,

**Comment by Divide-By-0** [comment]
@foolo good call, I've made them two separate issues!
