### ISSUE TITLE
Improve UX flow

### ISSUE THREAD

**Issue by foolo** [zkemail/archive.prove.email#68]
Yush G, [2024-03-27 09:41]
Also the sign in button should probably be on the main upload screen

Yush G, [2024-03-27 09:42]
And after that start should be the main button shown and be more prominent, and everything below only shown once start is clicked

Yush G, [2024-03-27 09:42]
Basically lead the users through a flow where it's clear what to click next

**Comment by foolo** [comment]
@Divide-By-0 I updated the flow a bit. I hope it made it a little more intuitive for the user.

**When the user is signed out, the upload page now looks like this:**

![Screenshot_2024-03-29_17-04-37](https://github.com/zkemail/registry.prove.email/assets/667227/a68df99f-f666-429e-8cc7-0ce78af417d3)

**When the user didn't give the full scope access:**
![Screenshot_2024-03-29_17-06-41](https://github.com/zkemail/registry.prove.email/assets/667227/95407bdb-c69e-4055-a1fc-a60c7e1ddf77)

**When the user is signed in, but has not started the upload:**
![Screenshot_2024-03-29_17-02-16](https://github.com/zkemail/registry.prove.email/assets/667227/de1b6dce-a217-4ebd-b00a-f2f94d8cab55)

**After the user clicked start:**
![Screenshot_2024-03-29_17-01-43](https://github.com/zkemail/registry.prove.email/assets/667227/fe60f242-a870-45ed-af8a-e08686cb189d)

**Comment by foolo** [comment]
@Divide-By-0 All feedback is welcome!

**Comment by Divide-By-0** [comment]
Hey! These improvements are great. One note I would add is to say, until google has verified our account, you'll have to manually click proceed then continue. 

Maybe here, you can say that email access tokens are only stored on the user's browser, the server does not store any tokens nor access any private email data. And these first 2 sentences about oauth 2.0 and jwts can move to the privacy policy, and hyperlink to that from here?

**Comment by foolo** [comment]
Yush G, [2024-04-01 10:22]
also for the manual flow, can you add full instructions i.e. click exactly these buttons to send the gmail email, receive an email with exactly this title, and exact instructions for what to do once you’ve got the email etc. and also that you only haev 1 week after they send the email to download ur dat

**Comment by foolo** [comment]
I updated the page a bit.
I assumed that by "you'll have to manually click proceed then continue" you referred to the step in the Google login flow, that has the option to "Go to DKIM Lookup (unsafe)".

This is how it looks now
![Screenshot_2024-04-01_17-04-27 (copy 1)](https://github.com/zkemail/registry.prove.email/assets/667227/393c447d-9e6a-4ba2-bb3d-112a3e2defc4)

Regarding:
> the server does not store any tokens nor access any private email data.

Note that while the server does not store any tokens, it _does_ have access to private email data, because it's the server that parses the email headers [here](https://github.com/zkemail/registry.prove.email/blob/main/dkim-lookup-app/src/app/api/gmail/route.ts#L9)

**Comment by foolo** [comment]
implemented
https://github.com/zkemail/registry.prove.email/commit/89764ea37dd6d4bae2aa2e80c91ed66f383f4045
https://github.com/zkemail/registry.prove.email/commit/abec082b55e9e7c5ed2d9d2ad4b038f8608d0b3b
