### ISSUE TITLE
Add the number of unique selectors on the about page

### ISSUE THREAD

**Issue by foolo** [zkemail/archive.prove.email#78]

**Comment by foolo** [comment]
fixed in https://github.com/zkemail/archive.prove.email/commit/f2e80680a4c6ec58d0c3140cda9a23ddb5e00b48

**Comment by Divide-By-0** [comment]
I don't see it live on the site? Can you also add a field for added new unique selectors at the bottom of the Gmail upload portal?

**Comment by foolo** [comment]
> I don't see it live on the site? Can you also add a field for added new unique selectors at the bottom of the Gmail upload portal?

@Divide-By-0 Now it's showing live on https://archive.prove.email/about , have a look!
I created a new issue for the Gmail upload, because it's not entirely trivial, I hope that's OK? see https://github.com/zkemail/archive.prove.email/issues/80
Feel free to close this issue if you think that all is good.
